version: "3.7"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./.docker/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: sales
      MYSQL_USER: sales
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
